### ISSUE TITLE
Invalid compatible shapes caused by op LogicalAnd in triplet_loss.py

### ISSUE THREAD

**Issue by pranoot** [vzxxbacq/speaker-recognition-papers#5]
Hi @vzxxbacq ,

Thanks a lot for sharing the work and codes for deep speaker. I was trying to run the script deep_speaker.py and I encountered some error. I have changed batch size to 4 and am not using any gpu for training, the _main() function is as follows. 

```
def _main():
    """
    Test model.
    """
    from pyasv.data_manage import DataManage
    from pyasv import Config
    import sys
    sys.path.append("../..")
    config = Config(name='deepspeaker', n_speaker=10, batch_size=4, n_gpu=0, max_step=20, is_big_dataset=False,
                 learning_rate=0.01, save_path='./dataset/save', conv_weight_decay=0.01, fc_weight_decay=0.01, bn_epsilon=1e-3 )
    x = np.random.random([120, 100, 64, 1])
    y = np.random.randint(0, 10, [120, 1])
    train = DataManage(x, y, config)

    x = np.random.random([64, 100, 64, 1])
    y = np.random.randint(0, 10, [64, 1])
    validation = DataManage(x, y, config)

    run(config, train, validation)
```

and the error i encountered is as follows :

```Traceback (most recent call last):
  File "deep_speaker.py", line 512, in <module>
    _main()
  File "deep_speaker.py", line 508, in _main
    run(config, train, validation)
  File "deep_speaker.py", line 459, in run
    _no_gpu(config, train, validation)
  File "deep_speaker.py", line 247, in _no_gpu
    feed_dict={x: batch_x, y: batch_y})
  File "/Users/Desktop/speaker_verification/speaker_env/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/Desktop/speaker_verification/speaker_env/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/Desktop/speaker_verification/speaker_env/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/Users/Desktop/speaker_verification/speaker_env/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [4,4] vs. [4,4,10]
	 [[Node: LogicalAnd = LogicalAnd[_device="/job:localhost/replica:0/task:0/device:CPU:0"](LogicalNot, Equal_1)]]

Caused by op u'LogicalAnd', defined at:
  File "deep_speaker.py", line 512, in <module>
    _main()
  File "deep_speaker.py", line 508, in _main
    run(config, train, validation)
  File "deep_speaker.py", line 459, in run
    _no_gpu(config, train, validation)
  File "deep_speaker.py", line 223, in _no_gpu
    model = DeepSpeaker(config=config, x=x, y=y)
  File "deep_speaker.py", line 49, in __init__
    self._build_train_graph(x, y)
  File "deep_speaker.py", line 80, in _build_train_graph
    self._loss = self._triplet_loss(output, y)
  File "deep_speaker.py", line 142, in _triplet_loss
    loss = triplet_loss.batch_hard_triplet_loss(targets, inp, 1.0)
  File "/speaker-recognition-papers/pyasv/loss/triplet_loss.py", line 239, in batch_hard_triplet_loss
    mask_anchor_positive = _get_anchor_positive_triplet_mask(labels)
  File "/speaker-recognition-papers/pyasv/loss/triplet_loss.py", line 94, in _get_anchor_positive_triplet_mask
    mask = tf.logical_and(indices_not_equal, labels_equal)
  File "/Users/Desktop/speaker_verification/speaker_env/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2401, in logical_and
    "LogicalAnd", x=x, y=y, name=name)
  File "/Users/Desktop/speaker_verification/speaker_env/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/Desktop/speaker_verification/speaker_env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/Users/Desktop/speaker_verification/speaker_env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [4,4] vs. [4,4,10]

```
I tried with even different number of speakers but it still is giving me this error. Can you please let me know why is it giving this error?

Thanks a lot !

**Comment by vzxxbacq** [comment]
Hello @pranoot , I'm gald to that my code is helpful to you.

In fact, this error is caused by one-hot encoding. It has been solved by adding `np.argmax(labels, axis=1)` . contact me if you still have question.

Thanks for your report.

**Comment by pranoot** [comment]
Hello @vzxxbacq ,
 
Thanks for the revert and the fix both were helpful and now that script is running without any bug. 

Now I am trying to train the same model on my own dataset.
I have few doubts can you please help me with the same.

1. For pre processing feature extraction in deep speaker I used ext_fbank_feature as specified in the paper. There is SLIDE_WINDOW present in it. Is it required and also if yes what should be the appropriate shape for the same? 
2. The shape of the input place holder is ( None, 100, 64, 1)  I want to know is 100 num of frames of individual clip, 64 the number of f-bank coefficients?
3. What should be the duration of individual clip which is used for training ?

Thank you very much! :)

**Comment by pranoot** [comment]
Oh cool got it !
Thanks a lot !! :D
